// components/Modals/Graphs/ChartTypes.ts

export const chartTypes = [
  "Vertical Bar Chart",
  "Horizontal Bar Chart",
  "Line Chart",
  "Pie Chart",
  "Area Chart",
  "Histogram",
  "Scatter Plot",
  "Scatter Plot With Fit Line",
  "Boxplot",
  "Vertical Stacked Bar Chart",
  "Horizontal Stacked Bar Chart",
  "Grouped Bar Chart",
  "Multiple Line Chart",
  "Error Bar Chart",
  "Stacked Area Chart",
  "Grouped Scatter Plot",
  "Dot Plot",
  "Population Pyramid",
  "Frequency Polygon",
  // "3D Bar Chart",
  "Clustered Error Bar Chart",
  "Scatter Plot Matrix",
  "Stacked Histogram",
  "Clustered Boxplot",
  "1-D Boxplot",
  "Simple Range Bar",
  "Clustered Range Bar",
  "High-Low-Close Chart",
  "Difference Area",
  "Vertical Bar & Line Chart",
  "Vertical Bar & Line Chart2",
  "Dual Axes Scatter Plot",
  "Drop Line Chart",
  "Summary Point Plot",
  "3D Bar Chart2",
  "Clustered 3D Bar Chart",
  "Stacked 3D Bar Chart",
  // "3D Bar Chart",
  // "Bar2",
  "3D Scatter Plot",
  "Grouped 3D Scatter Plot",

  // "Word Cloud",
] as const;

export type ChartType = (typeof chartTypes)[number];
